# LOTTO MAX Prediction

In [ ]:
import numpy as np
from random import choice
from scipy import stats

In [ ]:
print(choice([i for i in range(1,50) if i not in [2,5,7]]))

21


In [ ]:
num1 = choice([i for i in range(1,51)])
num2 = choice([i for i in range(1,51) if i not in [num1]])
num3 = choice([i for i in range(1,51) if i not in [num1, num2]])
num4 = choice([i for i in range(1,51) if i not in [num1, num2, num3]])
num5 = choice([i for i in range(1,51) if i not in [num1, num2, num3, num4]])
num6 = choice([i for i in range(1,51) if i not in [num1, num2, num3, num4, num5]])
num7 = choice([i for i in range(1,51) if i not in [num1, num2, num3, num4, num5, num6]])

a = np.array([num1, num2, num3, num4, num5, num6, num7])
b = np.array([num1+1, num2+1, num3+1, num4+1, num5+1, num6+1, num7+1])

In [ ]:
c = np.stack([a, b, [20, 0, 0 ,0 ,0, 0, 0], [0, 18, 0 ,0 ,0, 0, 0]])
print(c)

[[50  6  4 41 21 13 33]
 [51  7  5 42 22 14 34]
 [20  0  0  0  0  0  0]
 [ 0 18  0  0  0  0  0]]


In [ ]:
np.rint(4.4).astype(int)

4

In [ ]:
print(stats.mode(c)[0][0])

[0 0 0 0 0 0 0]


In [ ]:
np.rint(np.median(c, axis=0)).astype(int)

array([35,  6,  2, 20, 10,  6, 16])

In [ ]:
def gen_lotto(iterations):
  # initializing numpy shape array
  temp = np.array([0, 0, 0, 0, 0, 0, 0])

  # generating distinct numbers
  for i in range(iterations+1):
    num1 = choice([i for i in range(1,51)])
    num2 = choice([i for i in range(1,51) if i not in [num1]])
    num3 = choice([i for i in range(1,51) if i not in [num1, num2]])
    num4 = choice([i for i in range(1,51) if i not in [num1, num2, num3]])
    num5 = choice([i for i in range(1,51) if i not in [num1, num2, num3, num4]])
    num6 = choice([i for i in range(1,51) if i not in [num1, num2, num3, num4, num5]])
    num7 = choice([i for i in range(1,51) if i not in [num1, num2, num3, num4, num5, num6]])

    gen = np.sort(np.array([num1, num2, num3, num4, num5, num6, num7]))
    print("{}        PREDICTION #:{}".format(gen, i))
    temp = np.vstack([temp, gen])

  # delete temp row of zeros
  temp = np.delete(temp, (0), axis=0)

  # return the mean
  predmean = np.rint(np.mean(temp, axis=0)).astype(int)
  predmed = np.rint(np.median(temp, axis=0)).astype(int)
  predmode = stats.mode(temp)[0][0]
  print("\nFINAL PREDICTION 1: {}".format(predmean))
  print("\nFINAL PREDICTION 2: {}".format(predmed))
  print("\nFINAL PREDICTION 3: {}".format(predmode))

In [ ]:
d = np.array([0, 0 , 0])

In [ ]:
d = np.stack([d, [1, 2 , 3]])

In [ ]:
d

array([[0, 0, 0],
       [1, 2, 3]])

In [ ]:
d = np.vstack([d, [1, 2 , 3]])

In [ ]:
np.delete(d, (0), axis=0)

array([[1, 2, 3],
       [1, 2, 3]])

In [ ]:
gen_lotto(100)

[ 1 10 11 18 31 38 44]        PREDICTION #:0
[10 14 26 29 36 42 49]        PREDICTION #:1
[ 5  6  7 15 37 41 47]        PREDICTION #:2
[14 16 21 23 25 31 36]        PREDICTION #:3
[ 4 14 22 34 35 36 44]        PREDICTION #:4
[ 3  4 14 28 31 40 42]        PREDICTION #:5
[ 3 16 26 28 44 45 48]        PREDICTION #:6
[ 4 15 17 23 33 44 50]        PREDICTION #:7
[11 18 19 25 35 38 42]        PREDICTION #:8
[ 9 12 17 18 26 36 48]        PREDICTION #:9
[20 25 27 29 37 46 48]        PREDICTION #:10
[ 2  9 16 25 31 33 35]        PREDICTION #:11
[ 3 11 14 29 32 34 41]        PREDICTION #:12
[ 3  8 10 26 42 43 47]        PREDICTION #:13
[ 1 19 23 33 43 45 47]        PREDICTION #:14
[ 7 20 23 26 31 32 43]        PREDICTION #:15
[ 1  8  9 11 23 35 40]        PREDICTION #:16
[ 8 17 19 37 42 48 50]        PREDICTION #:17
[ 1  6 10 23 27 43 44]        PREDICTION #:18
[ 1  3  8 21 37 45 46]        PREDICTION #:19
[13 24 30 32 36 38 45]        PREDICTION #:20
[ 6  8 13 19 21 28 30]        PREDICTION #:2